# Generated by Django 4.0.5 on 2022-07-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_profile_skills_skill_description_skill_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='owner',
        ),
    ]
