# Generated by Django 4.0.5 on 2022-07-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
    ]
