# Generated by Django 4.0.5 on 2022-06-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='new_field',
            field=models.TextField(blank=True, null=True),
        ),
    ]
