# Generated by Django 4.0.5 on 2022-07-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_intro',
        ),
        migrations.RemoveField(
            model_name='project',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='project',
            name='vote_ratio',
        ),
        migrations.RemoveField(
            model_name='project',
            name='vote_total',
        ),
    ]
