# Generated by Django 4.0.5 on 2022-07-10 19:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_rename_demo_link_project_usefull_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('url', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='usefull_links',
        ),
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.ManyToManyField(blank=True, to='projects.link'),
        ),
    ]
