# Generated by Django 4.0.5 on 2022-07-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_link_remove_project_usefull_links_project_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
